### ISSUE TITLE
Contact Form, Silent Failure & Documentation

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#23]
The Contact Us form will silently fail for any number of reasons, including but probably not limited to:

1. attempting to send mail to an invalid e-mail recipient
2. attempting to send e-mail from an address which is not accepted by the receiving e-mail server
3. bounced e-mails due to mailbox full, etc.

Silent failure is bad.  Worse yet, the Contact Us form must be set in a way which may not be 100% obvious to everyone who first starts using Shiny, and there is no obvious documentation of the procedure:

1. Login as admin
2. Admin area
3. Pages
4. List form handlers
5. Edit Contact Form
6. Update "Email to" Field

**Comment by denny** [comment]
The 'email to' field isn't actually compulsory - if it's left blank, the code falls back to using the site_email set in the main config file.  I've updated the 'edit form handler' template and the example data to hopefully make this more obvious.

**Comment by wbraswell** [comment]
Have we added any kind of error messages so that we are not failing silently when there is an error of some kind?
