### ISSUE TITLE
Edit Contact Form, Template "None" Works But "contact.tt" Doesn't Work

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#27]
This is just weird and counter-intuitive.  It is not clear to me why a value of "None" works but "contact.tt" sends a blank e-mail body...

1. Admin Area
2. Pages
3. List Form Handlers
4. Edit Contact Form
5a. Template Drop-Down Box, "None" Works
5b. Template Drop-Down Box, "contact.tt" Sends Blank E-Mail Body

**Comment by denny** [comment]
I can't reproduce this - the steps above work fine for me, using the default demo database and templates.  If you're still seeing a problem, come and find me on IRC at some point so we can figure out where we're diverging.

**Comment by wbraswell** [comment]
I will have to look into it and let you know.
