### ISSUE TITLE
Documentation, Update Getting-Started

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#35]
Add info about:

1. Creating & Using Page Templates
2. Changing Newsletter E-Mail Addresses
3. Changing Contact Us Form E-Mail Address
4. Only 1 Shiny Using mod_perl, Many Shiny's Using fastcgi
5. Mail Server Requirement (Postfix, Sendmail, etc)
6. Perlbrew & local::lib Usage Notes
7. Apache User/Group File Permissions (www-data)

**Comment by denny** [comment]
I think 6 is probably a bit out of scope for the CMS documentation... did you have any particular pain points in mind?

3 was taken care of recently by the changes for #23.  I'll see if I can get the rest of it in the docs this evening.

**Comment by wbraswell** [comment]
I have written up extensive Catalyst & Shiny installation instructions for Ubuntu or other Debian-based systems, you can find it here:

https://github.com/wbraswell/lampuniversity.org/blob/master/docs/LAMP_install_notes.txt#L420-L649

I have also written up generic installation instructions for local::lib, which is of general interest to anyone installing complex Perl software such as Shiny; you should use local::lib if you have a good system Perl installed:

https://github.com/wbraswell/rperl/blob/master/INSTALL#L55-L64

For anyone who does NOT have a good system Perl installed, they should use Perlbrew INSTEAD of local::lib, so I have written up generic instructions for that as well:

https://github.com/wbraswell/rperl/blob/master/INSTALL#L66-L92

I think all of this is very, very pertinent to the "Install" section of the official Shiny documentation.
