### ISSUE TITLE
Edit Shop Item, Change Item Code (URL) Loads Error Page

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#39]
When I am editing an item in the shop, and I change the Item Code (or leave it blank to be auto-generated), and click Save, then I am sent to the "Please come back later" error page.

This is because the URL has changed, but it is still trying to send me to the old URL.

Once I go back to the Admin Area, then I see the URL has been updated, and I can then load it at the new URL.

**Comment by denny** [comment]
This has been fixed now when editing a shop item, but it remains an issue in several other areas of the site, so I'm going to leave this open for a bit longer as a reminder to myself.

**Comment by denny** [comment]
Fixed the same bug in the Form Handler code too, I think it's probably dead now  :)  If it does pop up elsewhere, open a new issue.

**Comment by wbraswell** [comment]
:+1:
