### ISSUE TITLE
Edit Shop Category, Blank URL Name Causes Non-User-Recoverable Error

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#40]
The Edit Shop Category page allows a blank value to be passed in the URL Name field, which in turn stores a blank value in the database and causes all related URLs to be messed up.  CMS admins can't even fix the error by re-editing the category, because the edit page is no longer available at any real URL.

I had to manually fix the entry in the "shop_category" table of the database.

**Comment by denny** [comment]
Fixed.

**Comment by wbraswell** [comment]
Wow, great, thanks!

**Comment by denny** [comment]
Better late than never.  ;)
