### ISSUE TITLE
CKEditor, Totally Broken With Javascript Error [CRITICAL]

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#44]
This is related to a now-closed issue:
https://github.com/denny/ShinyCMS/issues/34

The new install of CKEditor full package has totally broken the WYSIWYG editor, now it doesn't show up at all, there is just a blank page area where the CKEditor should be.  If I view the JavaScript console I can see several errors:

The value "device-width;" for key "width" is invalid, and has been ignored. edit:15

The value "1.0;" for key "initial-scale" was truncated to its numeric prefix. edit:15

The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix. edit:15

Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead. edit:15

Uncaught TypeError: Cannot read property 'ltr' of undefined ckeditor.js:589
CKEDITOR.plugins.add.init ckeditor.js:589
(anonymous function) ckeditor.js:241
p ckeditor.js:221
CKEDITOR.scriptLoader.load ckeditor.js:221
(anonymous function) ckeditor.js:240
(anonymous function) ckeditor.js:228
(anonymous function) ckeditor.js:226
p ckeditor.js:221
CKEDITOR.scriptLoader.load ckeditor.js:221
CKEDITOR.resourceManager.load ckeditor.js:226
g ckeditor.js:227
(anonymous function) ckeditor.js:228
p ckeditor.js:239
(anonymous function) ckeditor.js:238
(anonymous function) ckeditor.js:444
(anonymous function) ckeditor.js:226
p ckeditor.js:221
u ckeditor.js:221
t ckeditor.js:221
(anonymous function) ckeditor.js:222

**Comment by kevinyan815** [comment]
I can answer the problem “Uncaught TypeError: Cannot read property 'ltr'”, I encountered the same problem recently and basically it was caused by miss language file in lang directory(in customization do not select all languages).

So you need add one rule in you configuration

config.language = 'en' (file name in your lang directory);

and clear the browser cache as well.

**Comment by wbraswell** [comment]
Thanks for the insight, @kevinyan815 !
