### ISSUE TITLE
Need for Global Elements

### ISSUE THREAD

**Issue by richarddeanjohnson** [denny/ShinyCMS#51]
Denny,
I am working with Will Braswell at Auto-Parallel Technologies and we are making some very cool websites with ShinyCMS.  Our latest effort required me to modify the search.tt to show our search results in our site wrapper theme.  The search results work well and show in our template, but the header and footer have would-be-global elements that we have been able to include (and duplicate) on each page that we create.  For example, editable phone numbers, emails and company by-lines appear in the header and footer and we duplicate the elements on each page.  The problem is that there is no way to add the phone numbers, emails and by-lines to the themed search page.  If we had a place to enter elements globally I would not have to add them to each page and they would show up in our site wrapper header and footer.  Is there a way to add global elements currently?
Richard Johnson

**Comment by denny** [comment]
Hi Richard,

Sorry for the delayed reply; busy as ever here!  I hope you're getting along okay with ShinyCMS so far.

There are global elements, you can create and edit them in the admin area under Other -> Edit Shared Content.

Regards,
Denny
