### ISSUE TITLE
logo title

### ISSUE THREAD

**Issue by Hiranyaloka** [denny/ShinyCMS#55]
<div id="logo">
    <a href="/"><img src="/static/images/logo.jpg" alt="[% meta.title || 'ShinySite' %]"></a>
</div>

Makes more sense to use "c.config.site_name" for the logo alt tag.

**Comment by denny** [comment]
Changed, thanks.

**Comment by denny** [comment]
Whoops, wrong number in that commit.  That one actually fixed #54
