### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by Hiranyaloka** [denny/ShinyCMS#58]
I found that on ubuntu with nginx/fastcgi, the "location /static" section of the example nginx configuration actually prevented ShinyCMS from serving static content. When I removed that section, it just worked.

I also moved the socket to the tmp directory, seems like that is the traditional place for it.

**Comment by denny** [comment]
I've been thinking that ShinyCMS should probably have its own ShinyCMS/tmp/ directory, for dropping odds and ends in.  I'm assuming that would be more secure than having them all in the system /tmp folder, on a shared server.

Opinions welcome.  :)

**Comment by Hiranyaloka** [comment]
Yes I agree. That directory should be a configuration item. Until then, the example nginx should work with existing code.
