### ISSUE TITLE
Deleting user fails if outstanding confirmations exist

### ISSUE THREAD

**Issue by denny** [denny/ShinyCMS#6]
See title...  db constraint sort of fail.

**Comment by denny** [comment]
Just pushed a commit which hopefully removes all but the non-trivial user-generated content and associated metadata before attempting to delete a user account.  Still need to decide what to do about the non-trivial stuff - blog posts, transaction logs, etc.

**Comment by wbraswell** [comment]
Nice, will test on my next Shiny install.  :+1:
