### ISSUE TITLE
New User configuration

### ISSUE THREAD

**Issue by Hiranyaloka** [denny/ShinyCMS#61]
We need a way to configure the default role of the "new user". Either with an explicit "new user" role, or perhpas,  a configuration that specifies which role the new users inherit when they sign up.

The current default (no access) is certainly the safest choice.

**Comment by denny** [comment]
I think this ticket has been rendered irrelevant by the change from 'User' as a role to 'Active' as a flag.  Feel free to re-open it if I've missed the point.  :)
