### ISSUE TITLE
Numeric shop_item.code breaks; need to remove special case code

### ISSUE THREAD

**Issue by wbraswell** [denny/ShinyCMS#62]
When I tried to add an item (“Keyboard”), it failed with Catalyst’s error page being shown. The second time when I tried to add the same item, but with a different item code, again it failed the same way. However, http://dylansworld.net/admin/shop/list-items lists the item (“Keyboard”). Clicking “View” loads a page with the message “Specified item not found. Please try again.”. “Edit” errors out.

...

[error] Caught exception in ShinyCMS::Controller::Admin::Shop->get_item "Can't call method "shop_item_elements" on an undefined value at /home/wbraswell/public_html/dylansworld.net-latest/script/../lib/ShinyCMS/Controller/Admin/Shop.pm line 109.", referer: http://dylansworld.net/admin/shop/add-item

...

\<denny> you can't use all numeric item codes
\<denny> sorry!
\<willthechill> oh wow okay
\<denny> that's a holdover from when I was originally coding the shop to allow viewing of items via either their 'sku code' or their database ID
\<willthechill> well we need to somehow catch that instead of causing a weird error
\<willthechill> :)
\<denny> eventually I decided to only use the sku (once I started auto-filling it on item creation), but I haven't ripped out all the if/else blocks that look for numeric IDs and handle them specially
\<denny> we don't need to catch it, we need to remove all the code that special cases numeric IDs
\<denny> file an issue on github for that?
\<denny> or just file one for 'numeric shop item ID breaks stuff' and I can fill in details in comments
\<denny> sorry, that's a weird one  :)

**Comment by denny** [comment]
@wbraswell, I'd appreciate it if you could do a little testing on this one at some point; it was a relatively complicated change, lots of bits extracted and tidied up in both front-end and admin-side controllers.  I think I got it all right, but a second pair of eyes would be reassuring!  :)

**Comment by wbraswell** [comment]
Okay, I am in the process of working on my servers, at some point in the not-too-distant future I will get an updated copy of Shiny running and test out this issue.
