### ISSUE TITLE
cpanfile vs. Makefile.pl

### ISSUE THREAD

**Issue by davehodg** [denny/ShinyCMS#64]
This isn't really a bug. I'm currently living in a perlbrew/cpanm world, so having Makefile.pl talk about CPAN.pm jars with my mode of operation. These days I live much more in cpanfile world. I blame MIYAGAWA.

Feel free to close after spending 5 seconds pondering :)

**Comment by denny** [comment]
No, it's a fair point... it's been bugging me too.  I know the Makefile.PL is part of Catalyst's required files to some extent (see default boilerplate notice at the top of it), but I haven't experimented to see how much can be removed fro there and put into a cpanfile.  There's also the issue of duplication between the Dockerfile cpanm command and the Makefile.PL - if it were in a cpanfile then I could just use that for the Dockerfile cpanm command too, which would be neater.

Patches welcome!  :)

**Comment by davehodg** [comment]
I haven't looked at the docker stuff yet. Soon...

**Comment by davehodg** [comment]
OK, given that docker also has a lit of perl modules, we're now in three places. I'm thinking cpanfile as a template to generate the other two :)

**Comment by denny** [comment]
It looks like `cpanm --installdeps .` will work off of the Makefile.PL these days...
