### ISSUE TITLE
Docker misunderstanding

### ISSUE THREAD

**Issue by davehodg** [denny/ShinyCMS#67]
I'm misunderstanding docker I think.

- docker build -t shinycms .

This builds the docker image. I get that. Run it again and it builds the docker image again. Do I need to push it to dockerhub to stop it doing that repeatedly?

Also, I'm not convinced a cat app is the best thing to docker. It's just too large. It's a classic big ball of legacy. Unless we have a cat image on dockerhub as a base. But even then...

Finally, I see you do an EXPOSE 6174 towards the end. I can't connect to port 6174!

**Comment by denny** [comment]
I think you are misunderstanding Docker, yes.  Catch me on IRC to discuss?

**Comment by denny** [comment]
And/or, look at the docker-run script.

**Comment by davehodg** [comment]
If you were on irc ;)

I'll look at the script. Still docker n00b here.

**Comment by davehodg** [comment]
I get this:

$ ./shinycms-docker-run 
Unable to find image 'shinyideas/shinycms:latest' locally
latest: Pulling from shinyideas/shinycms
03e1855d4f31: Pull complete 
a3ed95caeb02: Pull complete 
090ae3d8abbb: Pull complete 
fdff870a3d99: Pull complete 
2cb237dc7dc7: Pull complete 
73e3a35a2401: Pull complete 
2ac43488f865: Pull complete 
68bd08fc8454: Pull complete 
Digest: sha256:fdbe359b20020a16fb8741ad9f7d0dcacd927683119f509d486ba32f37de2725
Status: Downloaded newer image for shinyideas/shinycms:latest
docker: Error response from daemon: Could not get container for ShinySQL_shiny.cms.
See 'docker run --help'.

**Comment by denny** [comment]
Look at ALL the Docker scripts  :-)  You need the MySQL container running first.
