### ISSUE TITLE
Would be nice to cache dependencies on Travis CI

### ISSUE THREAD

**Issue by denny** [denny/ShinyCMS#72]
On CircleCI we now cache the dependencies (CPAN modules) that are installed before testing each time, and only rebuild that cache if the Makefile.PL changes... otherwise that part of the filesystem is just restored from the previously-cached run, which saves us about 5 minutes per test run (so ~10 minutes instead of ~15).

I believe Travis CI has a similar feature, but at first glance the documentation didn't make sense to me... if anybody else has done this before (@davehodg ?) then it'd be great if you could add caching to the Travis config!  Otherwise I'll get to it eventually  :)

**Comment by denny** [comment]
(Tagging Dave because I think he added the original Travis config to this project)  (Thank you!)

**Comment by davehodg** [comment]
Sadly, no. I tend to regard Travis as a perl version laundering thing that runs in the background and shouts when something that goes wrong.

In other news I've been taken with GitLab recently.

Did you get closure on the ImageMagick thing that I stalled on? When I was dockerising, I went from CPAN to installing system modules. MUCH faster. Especially when using Catalyst.

**Comment by denny** [comment]
Closing this in light of Travis abandoning their commitment to open source when they changed owners recently. Sad stuff.
